# Generated by Django 3.2.18 on 2023-05-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='tarifa', max_digits=8, verbose_name='tarifa')),
                ('fechaDeInicio', models.DateField(help_text='fecha de inicio de clases', verbose_name='Fecha de inicio')),
                ('cupo', models.PositiveIntegerField(help_text='cantidad máxima de alumnos', verbose_name='cupo')),
                ('fechaDeBaja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(help_text='apellido', max_length=30, verbose_name='Apellido')),
                ('nombre', models.CharField(help_text='nombre', max_length=40, verbose_name='Nombre')),
                ('numeroDocumento', models.IntegerField(help_text='Número de documento', verbose_name='Número de documento')),
                ('telefono', models.CharField(help_text='Código de área y número de teléfono (sólo números)', max_length=20, verbose_name='Número de teléfono')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico', max_length=254, verbose_name='E-mail')),
                ('coberturaMedica', models.CharField(default=None, help_text='Empresa y plan de la cobertura médica', max_length=40, null=True, verbose_name='Cobertura médica')),
                ('numeroAfiliado', models.CharField(default=None, help_text='Número de afiliado de la cobertura médica (sólo números)', max_length=15, null=True, verbose_name='Número de afiliado')),
                ('fechaAlta', models.DateField(verbose_name='Fecha de alta')),
                ('fechaBaja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('paseLibre', models.BooleanField(help_text='Tiene pase libre? S/N', verbose_name='Tiene pase libre?')),
                ('fechaPagoPaseLibre', models.DateField(blank=True, null=True, verbose_name='Última fecha de pago del pase libre')),
                ('aptoFisico', models.BooleanField(help_text='Presenta apto físico? S/N', verbose_name='Apto físico')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='TipoDeActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la actividad', max_length=40, verbose_name='nombre')),
                ('titulo', models.CharField(default=None, help_text='Título para usar en páginas', max_length=40, null=True, verbose_name='título')),
                ('subtitulo', models.CharField(default=None, help_text='Subtítulo para usar en páginas', max_length=40, null=True, verbose_name='subtítulo')),
                ('descripcion', models.CharField(default=None, help_text='Texto descriptivo de la actividad', max_length=200, null=True, verbose_name='descripción')),
                ('imagen_de_portada', models.ImageField(help_text='Imagen para la portada', null=True, upload_to='imagenes/', verbose_name='Portada')),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'verbose_name_plural': 'tipos de actividad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipoDocumento', models.CharField(help_text='Tipo de documento', max_length=5, primary_key=True, serialize=False, verbose_name='Tipo de documento')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(help_text='apellido', max_length=30, verbose_name='Apellido')),
                ('nombre', models.CharField(help_text='nombre', max_length=40, verbose_name='Nombre')),
                ('numeroDocumento', models.IntegerField(help_text='Número de documento', verbose_name='Número de documento')),
                ('telefono', models.CharField(help_text='Código de área y número de teléfono (sólo números)', max_length=20, verbose_name='Número de teléfono')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico', max_length=254, verbose_name='E-mail')),
                ('coberturaMedica', models.CharField(default=None, help_text='Empresa y plan de la cobertura médica', max_length=40, null=True, verbose_name='Cobertura médica')),
                ('numeroAfiliado', models.CharField(default=None, help_text='Número de afiliado de la cobertura médica (sólo números)', max_length=15, null=True, verbose_name='Número de afiliado')),
                ('cuil', models.IntegerField(help_text='Cuil (sin guiones)', verbose_name='Cuil')),
                ('fechaAlta', models.DateField(verbose_name='Fecha de contratación')),
                ('fechaBaja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administracion.tipodocumento')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeInscripcion', models.DateField(help_text='última fecha de pago de la cuota', verbose_name='fecha de pago')),
                ('bonificacion', models.DecimalField(decimal_places=2, help_text='porcentaje de bonificación sobe la cuota mensual', max_digits=8, verbose_name='porcentaje de bonificación sobe la cuota mensual')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.actividad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
            ],
            options={
                'verbose_name': 'inscripción',
                'verbose_name_plural': 'inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lu', 'lunes'), ('ma', 'martes'), ('mi', 'miércoles'), ('ju', 'jueves'), ('vi', 'viernes'), ('sa', 'sábado'), ('do', 'domingo')], max_length=2)),
                ('horaInicio', models.TimeField(verbose_name='hora de inicio de la clase')),
                ('horaFin', models.TimeField(verbose_name='hora de finalización de la clase')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.actividad')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administracion.tipodocumento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='clientes',
            field=models.ManyToManyField(through='administracion.Inscripcion', to='administracion.Cliente'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administracion.profesor', verbose_name='id del profesor'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipoDeActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.tipodeactividad'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('actividad', 'cliente'), name='unique_actividad_cliente'),
        ),
    ]
